name: pdf_forge
description: "A powerful app to forge professional PDF documents from your images."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.9.0

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  image_picker: ^1.2.1
  provider: ^6.1.5+1
  pdf: ^3.11.3
  printing: ^5.14.2
  google_fonts: ^6.3.3
  image_cropper: ^11.0.0
  image: ^4.5.4
  pro_image_editor: ^11.15.2
  path_provider: ^2.1.5
  uuid: ^4.5.2
  shared_preferences: ^2.5.4
  share_plus: ^12.0.1
  intl: ^0.20.2
  reorderable_grid_view: ^2.2.8
  package_info_plus: ^9.0.0
  flutter_svg: ^2.2.3
  url_launcher: ^6.3.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/logo/
